################################################################################
# SERVICES
################################################################################
services:
  ##########################################################################
  # 1) Vite dev server (HMR) - stays running
  ##########################################################################
  prompt_vite:
    image: node:20-alpine
    container_name: prompt_vite
    working_dir: /app/frontend
    command: >
      sh -c "
        npm ci &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "
    volumes:
      - app-src:/app
    restart: unless-stopped
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Route ONLY Vite dev server paths on the SAME host to :5173
      - "traefik.http.routers.prompt-vite.rule=Host(`prompt.mytek.la`) && (PathPrefix(`/@vite`) || PathPrefix(`/src`) || PathPrefix(`/node_modules`) || PathPrefix(`/vite`) || PathPrefix(`/__vite_ping`) || PathPrefix(`/@id`) || PathPrefix(`/@fs`))"
      - "traefik.http.routers.prompt-vite.entrypoints=web,websecure"
      - "traefik.http.routers.prompt-vite.tls=true"
      - "traefik.http.routers.prompt-vite.tls.certresolver=leresolver"
      - "traefik.http.routers.prompt-vite.priority=100"
      - "traefik.http.services.prompt-vite.loadbalancer.server.port=5173"

      # Websocket support for HMR
      - "traefik.http.middlewares.prompt-vite-ws.headers.customRequestHeaders.Connection=Upgrade"
      - "traefik.http.middlewares.prompt-vite-ws.headers.customRequestHeaders.Upgrade=websocket"
      - "traefik.http.routers.prompt-vite.middlewares=prompt-vite-ws@docker"

  ##########################################################################
  # 2) Backend - Bitnami Laravel
  ##########################################################################
  prompt_backend:
    image: bitnami/laravel:11
    container_name: prompt_backend
    restart: unless-stopped
    depends_on:
      prompt_db:
        condition: service_healthy
      prompt_redis:
        condition: service_healthy
      prompt_vite:
        condition: service_started
    volumes:
      - /storage/dev/laravel12-vue3-tailwind4-boilerplate/backend:/app
      - /storage/dev/laravel12-vue3-tailwind4-boilerplate/.env:/app/.env
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:HGoBfFxKXoXEsDqkEDGnMZYFQMDVUVY7KJ9aHcLO9RU=

      DB_CONNECTION: mysql
      DB_HOST: prompt_db
      DB_PORT: 3306
      DB_DATABASE: app
      DB_USERNAME: app
      DB_PASSWORD: app

      # Let Bitnami's own entrypoint start Laravel on port 80
      LARAVEL_PORT_NUMBER: 80
    command: >
      sh -c "
        composer install --no-interaction --prefer-dist --no-scripts;
        chmod +x /app/docker/entrypoint.sh 2>/dev/null || true;
        /app/docker/entrypoint.sh;
        exec /opt/bitnami/scripts/laravel/run.sh
      "
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Main app on the SAME host
      - "traefik.http.routers.prompt.rule=Host(`prompt.mytek.la`)"
      - "traefik.http.routers.prompt.entrypoints=web,websecure"
      - "traefik.http.routers.prompt.tls=true"
      - "traefik.http.routers.prompt.tls.certresolver=leresolver"
      - "traefik.http.routers.prompt.priority=1"
      - "traefik.http.services.prompt.loadbalancer.server.port=80"

      ##################################################################
      # Optional: match toastedui cache/headers style
      ##################################################################
      - "traefik.http.middlewares.prompt-html-cache.headers.customResponseHeaders.Cache-Control=no-cache,no-store,must-revalidate"
      - "traefik.http.routers.prompt.middlewares=prompt-html-cache@docker"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  ##########################################################################
  # 3) MySQL
  ##########################################################################
  prompt_db:
    image: mysql:8.4
    container_name: prompt_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot --silent"]
      interval: 30s
      timeout: 10s
      retries: 5

  ##########################################################################
  # 4) Redis
  ##########################################################################
  prompt_redis:
    image: redis:7.4-alpine
    container_name: prompt_redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

################################################################################
# NETWORKS
################################################################################
networks:
  traefik:
    external: true
  default:
    driver: bridge

################################################################################
# VOLUMES
################################################################################
volumes:
  app-src:
    driver: local
    driver_opts:
      type: none
      device: /storage/dev/laravel12-vue3-tailwind4-boilerplate
      o: bind

  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: /storage/dev/laravel12-vue3-tailwind4-boilerplate/mysql_data
      o: bind

  redis-data:
    driver: local
    driver_opts:
      type: none
      device: /storage/dev/laravel12-vue3-tailwind4-boilerplate/redis_data
      o: bind
